spring.application.name=agendamento-medico

spring.datasource.url=jdbc:postgresql://postgres.railway.internal:5432/railway
spring.datasource.username=postgres
spring.datasource.password=HqhrfmCgjmQiBDEJhHtTlLCkiFfOlxJG

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=${PORT:8080}
server.address=0.0.0.0